name: CI

on:
  push:

jobs:
  archive-apple:
    name: Archive (Apple)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: ./build.sh

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output/
